spring:
  main:
    banner-mode: "off"
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  application:
    name: notification

  datasource:
    url: jdbc:postgresql://postgres:5432/eshop
    driver-class-name: org.postgresql.Driver
    platform: postgres
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect


  mail:
    host: smtp.gmail.com
    port: 587
    username: paveltseitlin@gmail.com
    password: panasonic123
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, loggers, logfile, metrics
  endpoint:
    shutdown:
      enabled: true

app:
  push:
    account_sid: ACffb38145b9c140cbcbff160dc18bfd1e
    auth_token: 33480ce54329c95467b57dceda3e6d07
    twilio_number: +12403292300

  jwt:
    signingkey: 123

